-- 122_topic_seed.sql
-- 20 initiale Themen aus Glossar + Tech-Tree für die Schwarm-Pipeline.

INSERT INTO public.topic_pool (title, source, source_ref, context_seed) VALUES
  ('Was ist ein Token?', 'glossary', 'Token',
   'Die kleinste Texteinheit eines Sprachmodells — ungefähr 3-4 Buchstaben. "Hallo" = 1 Token, "außergewöhnlich" = 3 Tokens.'),
  ('Wie funktioniert eine REST-API?', 'glossary', 'REST-API',
   'Die häufigste Art von API. Du fragst per URL etwas, kriegst die Antwort als JSON zurück. Wie eine Speisekarte mit konkreten Bestellungen.'),
  ('Was ist Quantisierung?', 'glossary', 'Quantisierung',
   'Sprachmodelle kleiner machen indem ihre Zahlen auf weniger Bits reduziert werden — von 32 auf 4 Bit. Folge: Modell passt auf ein Handy.'),
  ('Was ist RAG?', 'glossary', 'RAG',
   'Retrieval Augmented Generation. Statt das Modell alles wissen zu lassen, gibt man ihm nur passende Dokumente mit. Spart Tokens, holt aktuelle Daten rein.'),
  ('Was ist ein Embedding?', 'glossary', 'Embedding',
   'Ein Text in eine Liste von Zahlen umwandeln, sodass ähnliche Texte ähnliche Zahlen haben. Basis für semantische Suche.'),
  ('Wie funktionieren Hash-Funktionen?', 'glossary', 'Hash-Funktion',
   'Verwandelt einen beliebig langen Text in einen kurzen Fingerabdruck. Selbst kleinste Änderungen am Text ergeben einen komplett anderen Hash.'),
  ('Was ist k-Anonymity?', 'glossary', 'k-Anonymity',
   'Datenschutz-Trick: man sendet nur einen Teil des Hashes (z.B. ersten 5 Zeichen). Der Server liefert alle passenden Treffer, der Client filtert lokal.'),
  ('Was ist ein Webhook?', 'glossary', 'Webhook',
   'Eine URL bei dir die ein externes System anruft wenn etwas passiert. "Sag mir Bescheid wenn neue Nachricht kommt".'),
  ('Was ist Cron?', 'glossary', 'Cron',
   'Eine Zeitplan-Sprache. "* * * * *" heißt jede Minute, "0 8 * * *" heißt jeden Morgen 8 Uhr.'),
  ('Was ist OAuth?', 'glossary', 'OAuth',
   'Ein Verfahren wie du einer App erlaubst auf deinen Account zuzugreifen, ohne dein Passwort zu verraten.'),
  ('Was ist Prompt-Engineering?', 'glossary', 'Prompt-Engineering',
   'Die Kunst gute Prompts zu schreiben. Strukturierte Anweisungen, Beispiele, klare Rollen-Definition.'),
  ('Was ist Cosine-Similarity?', 'glossary', 'Cosine-Similarity',
   'Maß für Vektor-Ähnlichkeit zwischen -1 und 1. Bei Embeddings: nahe 1 = sehr ähnlich.'),
  ('Was ist pgvector?', 'glossary', 'pgvector',
   'PostgreSQL-Extension, die Vektor-Spalten + Ähnlichkeitssuche ergänzt. Eingebaut in Supabase, kein Zusatzdienst nötig.'),
  ('Was ist ein Sprachmodell?', 'glossary', 'Sprachmodell',
   'Auch LLM (Large Language Model). Ein neuronales Netz das auf Sprache trainiert wurde. Erzeugt Wort für Wort eine Antwort.'),
  ('Was bedeutet Inferenz?', 'glossary', 'Inferenz',
   'Der Moment in dem das Modell eine Antwort generiert. Im Gegensatz zum Training. Inferenz ist das was Tokens kostet.'),
  ('Was ist Free-Tier?', 'glossary', 'Free-Tier',
   'Die kostenlose Nutzungs-Stufe eines Anbieters. Meist mit Limits (z.B. "500 Calls/Tag").'),
  ('Was ist JSON?', 'glossary', 'JSON',
   'Ein Format um strukturierte Daten zu transportieren. Computer-lesbar aber auch von Menschen verstehbar.'),
  ('Was ist Crypto-Random?', 'glossary', 'Crypto-Random',
   'Sicherer Zufallszahlen-Generator vom Browser. Anders als Math.random() vorhersagbar — gut für Passwörter und Keys.'),
  ('Wie funktioniert das Kontext-Fenster?', 'glossary', 'Kontext-Fenster',
   'Wie viele Tokens ein Sprachmodell „auf einmal lesen\" kann. Bei großen Modellen oft 128.000 Tokens (ca. 100.000 Wörter).'),
  ('Was ist multilingual-e5?', 'glossary', 'multilingual-e5',
   'Embedding-Modell, das in 100+ Sprachen ähnliche Bedeutungen erkennt. Gratis über Hugging Face.')
ON CONFLICT DO NOTHING;
